name: nightly_build

on:
  push:
  # schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # 5 am UTC (11pm MDT the day before) every weekday night in MDT
    # - cron: '* 5 * * 2-6'

env:
  # This env var should enforce develop branch of all dependencies
  FAVOR_LOCAL_GEMS: true
  GEM_DEVELOPER_KEY: ${{ secrets.GEM_DEVELOPER_KEY }}

jobs:
  weeknight-tests:
    # ubuntu-latest works since https://github.com/rbenv/ruby-build/releases/tag/v20220710 (July 10, 2022)
    # https://github.com/rbenv/ruby-build/discussions/1940
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.6.1
    steps:
      - uses: actions/checkout@v3
      - name: Update gems
        run: |
          bundle update
          bundle exec certified-update
      - name: Run Rspec
        run: bundle exec rspec
      - name: Coveralls
      # coveralls action docs: https://github.com/marketplace/actions/coveralls-github-action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov/urbanopt-example-geojson-project.lcov"
